<?php
/**
 * @file
 * Install file for the profile_regpath module.
 */

/**
 * Implements hook_enable().
 */
function profile_regpath_enable() {
  backdrop_set_message(st('Profile Registration Path has been enabled. To configure profile registration paths, edit a profile type on the ' . l(t('Profile Types administration page'), 'admin/structure/profiles')), 'status');
}

/**
 * Implements update_last_removed().
 */
function profile_regpath_update_last_removed() {
  return 7134;
}

/**
 * Empty misleading column data to prevent faulty role assignment.
 */
function profile_regpath_update_1000() {
  // Previously role assignment on registration didn't work, but this column
  // potentially contains *all roles* because of a form key collision.
  // Reset to empty array as now assignment will work.
  $table_name = 'profile_regpath';
  if (db_table_exists('profile2_regpath')) {
    $table_name = 'profile2_regpath';
  }
  $empty = serialize(array());
  db_update($table_name)
    ->fields(array('roles' => $empty))
    ->execute();
}

/**
 * Rename database table from Drupal 7.
 */
function profile_regpath_update_1001() {
  // We need to make sure that D7 made it at least to
  // profile2_regpath_update_7133(), so "profile_type" is available.
  // Those update hooks never made it into stable releases, so this requires to
  // run the update hooks in D7 on the latest Drupal dev.
  if (db_table_exists('profile2_regpath')) {
    if (db_field_exists('profile2_regpath', 'profile_type')) {
      // Just in case.
      if (db_table_exists('profile_regpath')) {
        db_drop_table('profile_regpath');
      }
      db_rename_table('profile2_regpath', 'profile_regpath');
    }
    else {
      return 'Database table "profile2_regpath" exists, but an essential column is missing. Migration not possible.';
    }
  }
}

/**
 * Clean up old Drupal 7 record in system table.
 */
function profile_regpath_update_1002() {
  db_delete('system')
    ->condition('name', 'profile2_regpath')
    ->execute();
}

/**
 * Convert user roles to configuration files.
 */
function profile_regpath_update_1003() {
  if (!db_table_exists('profile_regpath')) {
    return;
  }

  $regpaths = db_query("SELECT * FROM {profile_regpath}");
  foreach ($regpaths as $row) {
    $regpath_data = array(
      'path' => $row->path,
      'roles' => unserialize($row->roles),
      'status' => $row->status,
      'weight' => $row->weight,
      'misc' => unserialize($row->misc),
    );

    // Save the new user role.
    $config = config('profile.type.' . $row->profile_type);
    $config->set('regpath', $regpath_data);
    $config->save();
  }

  db_drop_table('profile_regpath');
}
