<?php

/**
 * @file
 * Attach profile form to registration form according to path.
 *
 * @todo Create tests
 */

/**
 * Implements hook_menu().
 */
function profile_regpath_menu() {
  $items = array();

  $reg_paths = _profile_regpath_load_regpath();

  if ($reg_paths) {
    // Set menu items for each registration path.
    foreach ($reg_paths as $reg_path) {
      $path = $reg_path->path;

      // Add profile-specific administrative 'add user' page.
      $items['admin/people/prp-create/' . $path] = array(
        'title' => 'Add user (' . profile_regpath_get_profile_label($reg_path->profile_type) . ' profile)',
        'page callback' => '_profile_regpath_user_register',
        'page arguments' => array(
          'regpath' => $reg_path,
        ),
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_ACTION,
        'file' => 'registration_form.inc',
      );

      // Create registration pages for each profile type.
      // We will use hook_menu_alter() to deal with the 'user/' path later.
      if ($path != 'user') {
        $registration_path = $path . '/register';

        $items[$registration_path] = array(
          'title' => 'Create new account',
          'page callback' => '_profile_regpath_user_register',
          'page arguments' => array(
            'regpath' => $reg_path,
          ),
          'access callback' => 'user_register_access',
          'file' => 'registration_form.inc',
          'type' => MENU_LOCAL_TASK,
        );
        $items[$path] = array(
          'title' => 'Log in',
          'page callback' => '_profile_regpath_user_login',
          'page arguments' => array(
            'regpath' => $reg_path,
          ),
          'access callback' => 'user_is_anonymous',
          'file' => 'registration_form.inc',
          'menu_name' => 'user-menu',
          'type' => MENU_CALLBACK,
        );
        $items[$path . '/login'] = array(
          'title' => 'Log in',
          'page callback' => '_profile_regpath_user_login',
          'page arguments' => array(
            'regpath' => $reg_path,
          ),
          'access callback' => 'user_is_anonymous',
          'file' => 'registration_form.inc',
          'type' => MENU_DEFAULT_LOCAL_TASK,
        );
        $items[$path . '/password'] = array(
          'title' => 'Request new password',
          'type' => MENU_LOCAL_TASK,
          'page callback' => '_profile_regpath_user_password',
          'page arguments' => array(
            'regpath' => $reg_path,
          ),
          'access callback' => 'user_is_anonymous',
          'file' => 'registration_form.inc',
        );
      }
    }
  }
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function profile_regpath_menu_alter(&$items) {
  // Check to see if the default 'user' path is being used with Profile.
  if ($user_paths = _profile_regpath_load_regpath('user')) {
    $regpath = array_shift($user_paths);
    // Build form at user/register using _profile_regpath_user_register().
    $items['user/register']['page callback'] = '_profile_regpath_user_register';
    $items['user/register']['page arguments'] = array('regpath' => $regpath);
    $items['user/register']['file'] = 'registration_form.inc';
    $items['user/register']['file path'] = backdrop_get_path('module', 'profile_regpath');

    return $items;
  }
}

/**
 * Implements hook_permission().
 */
function profile_regpath_permission() {
  $permissions = array(
    'administer profile_regpath' => array(
      'title' => t('Administer Profile registration paths'),
      'description' => t('Enable and configure unique registration paths per Profile profile type.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function profile_regpath_form_profile_type_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'profile_regpath', 'profile_regpath.admin');
  _profile_regpath_form_profile_type_form_alter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_alter().
 */
function profile_regpath_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    module_load_include('inc', 'profile_regpath');

    // Logintoboggan might display user_register_form on 403 pages.
    if (module_exists('logintoboggan') && config_get('system.performance', 'site_403') == 'toboggan/denied' && strpos(backdrop_get_http_header('Status'), '403') === 0) {
      $profile_types = _profile_regpath_load_regpath('user');
    }
    else {
      // Get profile types from current path.
      $url = backdrop_parse_url($form['#action']);
      $path = ltrim($url['path'], '/');

      // Check to see if this is an alias. If so, use source path.
      if ($source = backdrop_lookup_path('source', $path)) {
        $path = $source;
      }

      $path_parts = explode('/', $path);
      if (count($path_parts) == 4 && $path_parts[2] == 'prp-create') {
        // Admin form - last path part.
        $path_key = end($path_parts);
      }
      else {
        // Register form for anonymous - first path part.
        $path_key = reset($path_parts);
      }

      // Load profiles registration path data for this path key and attach associated fields.
      $profile_types = _profile_regpath_load_regpath($path_key, 1);
    }
    profile_regpath_attach_profile_fields($form, $form_state, $form_id, $profile_types);
  }
}

/**
 * Implements hook_user_insert().
 */
function profile_regpath_user_insert($account) {
  // Show custom confirmation message.
  if (isset($_SESSION['profile_regpath']['confirmation_message'])) {
    backdrop_set_message(filter_xss($_SESSION['profile_regpath']['confirmation_message']));
    unset($_SESSION['profile_regpath']['confirmation_message']);
  }
}

/**
 * Provides profile_id by profile machine_name.
 *
 * @param string $profile_type
 *   Machine-name of profile profile type.
 *
 * @return string
 *   The profile id for indicated profile type.
 */
function profile_regpath_get_profile_id($profile_type) {
  $data = config_get('profile.type.' . $profile_type);
  return $data['type'];
}

/**
 * Provides label by profile machine_name.
 *
 * @param string $profile_type
 *   Machine-name of profile type.
 *
 * @return string
 *   The label for indicated profile type.
 */
function profile_regpath_get_profile_label($profile_type) {
  $config = config('profile.type.' . $profile_type);
  return $config->get('label');
}

/**
 * Registration path data.
 *
 * @param string $path
 *    (optional) path value. Defaults to NULL.
 * @param string $status
 *    (optional) status of path. Defaults to NULL.
 *
 * @return array
 *    An array containing all matching profile registration path enabled
 *    profile types.
 */
function _profile_regpath_load_regpath($path = NULL, $status = NULL) {
  $profile_types_config = config_get_names_with_prefix('profile.type.');

  $profile_types = array();
  foreach ($profile_types_config as $type) {
    $config = config('profile.type.' . $type);
    $config_path = $config->get('regpath.path');
    $is_path = $path == NULL || $path == $config_path;
    $config_status = $config->get('regpath.status');
    $is_status = $status == NULL || $status == $config_status;

    $data = $config->get('regpath');
    if ($is_path && $is_status && $data) {
      $data += array(
        'profile_type' => $type,
      );
      $profile_types[$type] = (object) $data;
    }
  }

  backdrop_sort($profile_types, array('weight'));
  return $profile_types;
}

/**
 * Save a single regpath.
 *
 * @param array $regpath
 */
function profile_regpath_regpath_save($regpath) {
  $config = config('profile.type.' . $regpath['profile_type']);
  unset($regpath['profile_type']);
  unset($regpath['profile_id']);
  $config->set('regpath', $regpath);
  $config->save();
}
